apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
       containers:
         - name: medicure
           image: aditya3328/medicure:latest
           ports:
             - containerPort: 8081
               
